services:
  postgres:
    image: postgres:16-alpine
    container_name: dentalbot-postgres

    environment:
      POSTGRES_DB: dentalbot
      POSTGRES_USER: dentalbot
      POSTGRES_PASSWORD: dentalBot@123

    ports:
      - "5433:5432"

    volumes:
      - dentalbot_postgres_data:/var/lib/postgresql/data

volumes:
  dentalbot_postgres_data: