services:
  postgres:
    image: postgres:16-alpine
    container_name: dentalbot-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - dentalbot_postgres_data:/var/lib/postgresql/data

volumes:
  dentalbot_postgres_data: