spring:
  application:
    name: dentalbot

  datasource:
    url: jdbc:postgresql://localhost:5433/dentalbot
    username: dentalbot
    password: dentalBot@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: NX06dc1usR24Jz+DPXJKehus6PaSAJ6T3ZLJCd8xMB4=d
  expiration: 86400000

logging:
  level:
    org.springframework.security: INFO